backend:
  name: github
  repo: singhremo00-commits/remosingh.in
  branch: main
  auth_type: implicit

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Post Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Short Description (SEO & AI Summary)", name: "description", widget: "string" }
      - { label: "Featured Image / Poster", name: "thumbnail", widget: "image", required: false }
      - { label: "Article Body", name: "body", widget: "markdown" }
      
